title: Sam Popowich
description: 

url: http://redlibrarian.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: CV
   url: /cv.html
 - title: Publications
   url: /publications.html
 - title: Presentations
   url: presentations.html
 - title: Contact
   url: /contact

social:
   github: redlibrarian
   twitter: redlibrarian
   facebook: sam.popowich
   email: spopowich@gmail.com

google_analytics: ""
