# Site settings
name: redlibrarian
title: redlibrarian
email: spopowich at gmail dot com
description: ""
#baseurl: "/"
url: "https://redlibrarian.github.io"

# Build settings
markdown: kramdown
permalink: pretty

urls:
  - text: computational musicology
    url: /compmus
  - text: ruby
    url: /ruby
