# Site settings
name: redlibrarian
title: redlibrarian
email: spopowich at gmail dot com
description: ""
baseurl: "https://redlibrarian.github.io"
url: "https://redlibrarian.github.io"

# Build settings
markdown: kramdown
permalink: pretty

urls:
  - text: computational musicology
    url: /compmus.html
  - text: ruby
    url: /ruby
